version: "3.7"

services:
  prom-relabel-proxy:
    container_name: prom-relabel-proxy
    build: .
    ports:
      - 9091:9091
    restart: unless-stopped
    volumes:
      - ./config:/config
    command: -c /config/relabel.yaml
