scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ["prometheus:9090"]
    relabel_configs:
      - source_labels: [__name__]
        regex: "prometheus_http_requests_total"
        target_label: handler
        replacement: ""
      - source_labels: [__name__]
        regex: "prometheus_http_requests_total"
        target_label: "added_label"
        replacement: "example"
